- platform: uk_transport
  app_id: !secret uk_transport_id
  app_key: !secret uk_transport_key
  queries:
    - mode: bus
      origin: 6200201000
      destination: Leith Links, Edinburgh
    - mode: bus
      origin: 6200246840
      destination: Edinburgh Airport

# - platform: template
#   sensors:
#     next_bus_route:
#       friendly_name: 'Next bus route'
#       value_template: "{{state_attr('sensor.next_bus_to_fountainbridge', 'next_buses')[0].route}}"
#     next_bus_direction:
#       friendly_name: 'Next bus direction'
#       value_template: "{{state_attr('sensor.next_bus_to_fountainbridge', 'next_buses')[0].direction}}"
#     next_bus_scheduled:
#       friendly_name: 'Next bus scheduled'
#       value_template: "{{state_attr('sensor.next_bus_to_fountainbridge', 'next_buses')[0].scheduled}}"
#     next_bus_estimated:
#       friendly_name: 'Next bus estimated'
#       value_template: "{{state_attr('sensor.next_bus_to_fountainbridge', 'next_buses')[0].estimated}}"
