- platform: template
  sensors:
    recycling_bin_tomorrow:
      entity_id: []
      friendly_name: "Recycling Bin Tomorrow"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2020-01-09 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/recycling_bin_tomorrow.png'}}
    recycling_bin_today:
      entity_id: []
      friendly_name: "Recycling Bin Today"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2020-01-10 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/recycling_bin_today.png'}}
    landfill_bin_tomorrow:
      entity_id: []
      friendly_name: "Landfill Bin Tomorrow"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2020-01-16 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/landfill_waste_bin_tomorrow.png'}}
    landfill_bin_today:
      entity_id: []
      friendly_name: "Landfill Bin Today"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2020-01-17 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/landfill_waste_bin_today.png'}}
    garden_bin_tomorrow:
      entity_id: []
      friendly_name: "Garden Bin Tomorrow"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2020-05-12 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/garden_waste_bin_tomorrow.png'}}
    garden_bin_today:
      entity_id: []
      friendly_name: "Garden Bin Today"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2020-05-13 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/garden_waste_bin_today.png'}}

