- platform: template
  sensors:
    recycling_bin_tomorrow:
      entity_id: []
      friendly_name: "Recycling Bin Tomorrow"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2019-06-13 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/recycling_bin_tomorrow.png'}}
    recycling_bin_today:
      entity_id: []
      friendly_name: "Recycling Bin Today"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2019-06-14 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/recycling_bin_today.png'}}
    landfill_bin_tomorrow:
      entity_id: []
      friendly_name: "Landfill Bin Tomorrow"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2019-06-20 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/landfill_waste_bin_tomorrow.png'}}
    landfill_bin_today:
      entity_id: []
      friendly_name: "Landfill Bin Today"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2019-06-21 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/landfill_waste_bin_today.png'}}
    garden_bin_tomorrow:
      entity_id: []
      friendly_name: "Garden Bin Tomorrow"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2019-06-11 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/garden_waste_bin_tomorrow.png'}}
    garden_bin_today:
      entity_id: []
      friendly_name: "Garden Bin Today"
      value_template: "{{ ((as_timestamp(now()) - as_timestamp('2019-06-12 00:00:00'))) / 86400 |int % 14 < 1 }}"
      entity_picture_template: >-
        {{ '/local/icons/recyclinggreenbin/garden_waste_bin_today.png'}}

