- platform: template
  sensors:
    mouse_trap_one_status:
      value_template: >
        {% if states.binary_sensor.mouse_trap_one_contact.state == "on" %}
          Mouse Caught
        {% else %}
          Trap Set
        {% endif %}
      friendly_name: 'Mouse Killer One'
      icon_template: 'mdi:mouse-variant'

- platform: template
  sensors:
    mouse_trap_two_status:
      value_template: >
        {% if states.binary_sensor.mouse_trap_two_contact.state == "on" %}
          Mouse Caught
        {% else %}
          Trap Set
        {% endif %}
      friendly_name: 'Mouse Killer Two'
      icon_template: 'mdi:mouse-variant'