homeassistant:
  # Name of the location where Home Assistant is running
#  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 45
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named config/packages


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

stream:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.13.254
    - 127.0.0.1
    - ::1
    - 192.168.13.0/24
# api_password: !secret http_password
#  base_url: https://home.yeradonkey.com
  #IP ban dissabled while X-Forwarded-For is broken to prevent blocking reverse proxy
  #  ip_ban_enabled: true
  #  login_attempts_threshold: 5

# Discover some devices automatically
discovery:
  ignore: 
    - kodi
    - yamaha
# Enable Home Assistant to send Wake-on-lan packets
wake_on_lan:

# enable the ios integrations
ios:

# enable broadlink smartir platform
#smartir:

# enable the mobile app
mobile_app:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    # cache: true
    # cache_dir: /tmp/tts
    # time_memory: 300
    # base_url: https://home.yeradonkey.com
    # service_name: google_say

hacs:
  token: !secret hacs_token

# pi_hole:
#   host: localhost:4865

# New fancy coloured ui logging
#uilogs:

webhook:

#feedreader:
#  urls:
#    - https://www.home-assistant.io/atom.xml
#    - https://hasspodcast.io/feed/podcast
#    - https://www.edinburghlive.co.uk/all-about/coronavirus?service=rss

################################################################################
#                                    Includes                                  #
################################################################################

#!include_dir_merge_named config/iframes
group: !include_dir_merge_named config/groups
notify: !include_dir_merge_list config/notify
automation: !include automations.yaml
script: !include scripts.yaml
#panel_iframe: !include_dir_merge_named config/frontend/iframes/
# Devices
climate: !include config/devices/heating/heatmiser.yaml
nest: !include config/devices/smoke/nest.yaml
sensor: !include_dir_merge_list config/devices/sensors
binary_sensor: !include_dir_merge_list config/devices/binary_sensors
light: !include_dir_merge_list config/devices/lights/
switch: !include_dir_merge_list config/devices/switches
camera: !include_dir_merge_list config/devices/camera/
#xiaomi_aqara: !include_dir_merge_named config/devices/gateways
# Core
influxdb: !include config/core/influx.yaml
recorder: !include config/core/recorder.yaml
feedreader: !include config/core/feedreader.yaml
logger: !include config/core/logger.yaml
calendar: !include config/core/calendar.yaml
# logbook: !include config/core/logbook.yaml
# ourgroceries: !include config/core/ourgroceries.yaml
media_player: !include_dir_merge_list config/mediaplayers
shell_command: !include_dir_merge_list config/shell_commands/
timer: !include_dir_merge_named config/timers/
#zone: !include config/core/zones.yaml
################################################################################
#                                    Alarm System                              #
################################################################################
#alarm_control_panel: !include alarm.yaml
#panel_custom: !include panel_custom.yaml
alarm_control_panel: !include resources/bwalarm/bwalarm.yaml



################################################################################
#                                    Inputs                                    #
################################################################################
input_boolean: !include_dir_merge_named config/inputs/input_boolean
input_datetime: !include_dir_merge_named config/inputs/input_datetime
input_number: !include_dir_merge_named config/inputs/input_number
input_select: !include_dir_merge_named config/inputs/input_select
input_text: !include_dir_merge_named config/inputs/input_text

################################################################################
#                                    frontend                                  #
################################################################################
frontend:
  themes: !include_dir_merge_named themes
  
  #extra_html_url:
    #- /local/icons/fontawesome/hass-fontawesome-solid.html
    #- /local/icons/bha-icons/hass-bha-icons.html
  #javascript_version: auto

# entity_controller:
#   motion_night_light:
#    sensor: binary_sensor.squiggley_nightlight_motion_sensor_occupancy
#    entity: light.nightlight_stripper
#    delay: 600                            
#    service_data: 
#      brightness: 90