icon: 'fas:bed'
title: SquiggleBear Bedroom
background: var(--background-image)
badges: []
cards:
  - card:
      title: Door/Window/Motion Sensors
      type: glance
    entities:
      - binary_sensor.bedroom_window_one_sensor
      - binary_sensor.bedroom_window_two_sensor
      - binary_sensor.large_wardrobe_one_motion_sensor
      - binary_sensor.large_wardrobe_two_motion_sensor
      - binary_sensor.small_wardrobe_motion_sensor
      - binary_sensor.squiggley_nightlight_motion_sensor
      - binary_sensor.squiggley_wee_bear_motion_sensor
    id: door_window_open
    show_empty: false
    show_header_toggle: false
    state_filter:
      - open
      - 'on'
    type: 'custom:hui-entity-filter-card'
  - cards:
      - color: auto
        color_type: icon
        entity: light.large_wardrobe_stripper
        haptic: medium
        hold_action:
          action: more-info
          entity_id: light.large_wardrobe_stripper
        icon: 'bha:led-strip'
        name: Wee Bear Wardrobe
        tap_action:
          action: call-service
          service: light.toggle
          service_data:
            entity_id: light.large_wardrobe_stripper
        type: 'custom:button-card'
      - color: auto
        color_type: icon
        entity: light.small_wardrobe_stripper
        haptic: medium
        hold_action:
          action: more-info
          entity_id: small.large_wardrobe_stripper
        icon: 'bha:led-strip'
        name: Squiggley Wardrobe
        tap_action:
          action: call-service
          service: light.toggle
          service_data:
            entity_id: light.small_wardrobe_stripper
        type: 'custom:button-card'
      - color: auto
        color_type: icon
        entity: light.nightlight_stripper
        haptic: medium
        hold_action:
          action: more-info
          entity_id: light.nightlight_stripper
        icon: 'bha:led-strip'
        name: Nightlight Stripper
        tap_action:
          action: call-service
          service: light.toggle
          service_data:
            entity_id: light.nightlight_stripper
        type: 'custom:button-card'
    type: 'custom:hui-horizontal-stack-card'
  - entity: climate.bedroom
    type: 'custom:hui-thermostat-card'
  - entities:
      - entity: media_player.zaphod
        group: true
        info: scroll
        source: icon
        type: 'custom:mini-media-player'
      - entity: media_player.bedroom_speaker
        group: true
        info: scroll
        type: 'custom:mini-media-player'
    type: 'custom:hui-entities-card'
  - entities:
      - entity: sensor.squiggley_bed_sensor_2
    type: entities
  - entity: media_player.squiggleytv_ue40es5500
    type: media-control
