icon: 'fas:utensils'
title: Kitchen
background: var(--background-image)
badges: []
cards:
  - cards:
      - color: auto
        color_type: icon
        entity: light.kitchen_strippers
        haptic: medium
        hold_action:
          action: more-info
          entity_id: light.kitchen_strippers
        icon: 'bha:led-strip'
        name: Kitchen Strippers
        tap_action:
          action: call-service
          service: light.toggle
          service_data:
            entity_id: light.kitchen_strippers
        type: 'custom:button-card'
      - color: green
        color_type: icon
        entity: switch.kitchen_tree_relay
        haptic: medium
        icon: 'fas:tree'
        name: Tree
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.kitchen_tree_relay
        type: 'custom:button-card'
    type: 'custom:hui-horizontal-stack-card'
  - entity: climate.kitchen
    type: thermostat
  - entities:
      - artwork: cover
        background: transparent
        entity: media_player.rasplex
        group: true
        info: scroll
        power_color: true
        show_progress: true
        show_source: full
        source: icon
        type: 'custom:mini-media-player'
      - artwork: cover
        entity: media_player.noisemaker
        group: true
        info: scroll
        power_color: true
        show_progress: true
        show_source: full
        type: 'custom:mini-media-player'
      - entity: media_player.kitchen_speaker
        group: true
        info: scroll
        type: 'custom:mini-media-player'
    type: entities
  - cards:
      - cards:
          - color: auto
            color_type: icon
            entity: switch.spiral_lights
            haptic: medium
            hold_action:
              action: more-info
              entity_id: switch.spiral_lights
            icon: 'fas:lightbulb'
            name: Wall Lights On/Off
            tap_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.spiral_lights
            type: 'custom:button-card'
          - color: auto
            color_type: icon
            entity: switch.spiral_lights_brighter
            haptic: medium
            icon: 'mdi:lightbulb-on-outline'
            name: Brighter
            tap_action:
              action: call-service
              service: switch.turn_on
              service_data:
                entity_id: switch.spiral_lights_brighter
            type: 'custom:button-card'
          - color: auto
            color_type: icon
            entity: switch.spiral_lights_darker
            haptic: medium
            icon: 'mdi:lightbulb-outline'
            name: Darker
            tap_action:
              action: call-service
              service: switch.turn_on
              service_data:
                entity_id: switch.spiral_lights_darker
            type: 'custom:button-card'
        type: horizontal-stack
      - cards:
          - color: red
            color_type: icon
            entity: switch.spiral_lights_red
            haptic: medium
            hold_action:
              action: more-info
              entity_id: switch.spiral_lights_red
            icon: 'fas:palette'
            name: Red
            tap_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.spiral_lights_red
            type: 'custom:button-card'
          - color: green
            color_type: icon
            entity: switch.spiral_lights_green
            haptic: medium
            hold_action:
              action: more-info
              entity_id: switch.spiral_lights_green
            icon: 'fas:palette'
            name: Green
            tap_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.spiral_lights_red
            type: 'custom:button-card'
          - color: blue
            color_type: icon
            entity: switch.spiral_lights_blue
            haptic: medium
            hold_action:
              action: more-info
              entity_id: switch.spiral_lights_blue
            icon: 'fas:palette'
            name: Blue
            tap_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.spiral_lights_blue
            type: 'custom:button-card'
          - color: turquoise
            color_type: icon
            entity: switch.spiral_lights_turquoise
            haptic: medium
            hold_action:
              action: more-info
              entity_id: switch.spiral_lights_turquoise
            icon: 'fas:palette'
            name: Turuoise
            tap_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.spiral_lights_turquoise
            type: 'custom:button-card'
        type: horizontal-stack
    type: 'custom:hui-vertical-stack-card'
  - entities:
      - entity: sensor.mouse_trap_one_status
      - entity: sensor.mouse_trap_two_status
    show_header_toggle: false
    title: Mouse Traps
    type: entities
  - cards:
      - entities:
          - input_boolean.slow_cooker_timer
          - input_datetime.slow_cooker_start
          - input_datetime.slow_cooker_stop
        show_header_toggle: false
        title: Slow Cooker Controls
        type: entities
      - color: auto
        color_type: icon
        entity: switch.ambilight_relay
        haptic: medium
        hold_action:
          action: more-info
          entity_id: switch.ambilight_relay
        icon: 'mdi:stove'
        name: Slow Cooker Status
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.ambilight_relay
        type: 'custom:button-card'
    type: 'custom:hui-vertical-stack-card'
