icon: 'fas:couch'
title: Livingroom
background: var(--background-image)
badges: []
cards:
  - cards:
      - color: transparent
        color_type: card
        entity_id: script.activate_moron_machine
        icon: 'fas:tv'
        name: Moron Machine On
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.activate_moron_machine
        type: 'custom:button-card'
      - color: transparent
        color_type: card
        entity_id: script.deactivate_moron_machine
        icon: 'fas:tv'
        name: Moron Machine Off
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.deactivate_moron_machine
        type: 'custom:button-card'
    type: horizontal-stack
  - entities:
      - background: transparent
        entity: media_player.marvin
        group: true
        hide:
          volume: true
        info: scroll
        type: 'custom:mini-media-player'
      - entity: media_player.livingroom_tv
        group: true
        hide:
          controls: true
          volume: true
        info: scroll
        type: 'custom:mini-media-player'
      - entity: media_player.squiggley_amp
        group: true
        hide:
          controls: true
        info: scroll
        sound_mode: full
        type: 'custom:mini-media-player'
        volume_stateless: true
      - entity: media_player.livingroom_speaker
        group: true
        info: scroll
        type: 'custom:mini-media-player'
    type: entities
  - cards:
      - cards:
          - color: transparent
            color_type: card
            entity: media_player.livingroom_tv
            haptic: medium
            icon: 'fas:tv'
            name: TV On
            tap_action:
              action: call-service
              service: media_player.turn_on
              service_data:
                entity_id: media_player.livingroom_tv
            type: 'custom:button-card'
          - color: transparent
            color_type: card
            entity: media_player.livingroom_tv
            haptic: medium
            icon: 'fas:tv'
            name: TV Off
            tap_action:
              action: call-service
              service: media_player.turn_off
              service_data:
                entity_id: media_player.livingroom_tv
            type: 'custom:button-card'
        type: 'custom:hui-horizontal-stack-card'
      - cards:
          - color: transparent
            color_type: card
            entity: media_player.squiggley_amp
            haptic: medium
            icon: 'fas:sliders-h'
            name: Amp On
            tap_action:
              action: call-service
              service: media_player.turn_on
              service_data:
                entity_id: media_player.squiggley_amp
            type: 'custom:button-card'
          - color: transparent
            color_type: card
            entity: media_player.squiggley_amp
            haptic: medium
            icon: 'fas:sliders-h'
            name: Amp Off
            tap_action:
              action: call-service
              service: media_player.turn_off
              service_data:
                entity_id: media_player.squiggley_amp
            type: 'custom:button-card'
          - color: auto
            color_type: icon
            entity: switch.ambilight_relay
            haptic: medium
            hold_action:
              action: more-info
              entity_id: switch.ambilight_relay
            icon: 'bha:led-strip'
            name: Ambilight
            tap_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.ambilight_relay
            type: 'custom:button-card'
        type: 'custom:hui-horizontal-stack-card'
    type: 'custom:hui-vertical-stack-card'
  - entity: climate.livingroom
    name: Livingroom
    type: thermostat
  - card:
      cards:
        - cards:
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/volumedown-button.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_volume_down
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/mute-button.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_mute
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/volumeup-button.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_volume_up
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/kodi-icon.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              type: 'custom:button-card'
          type: 'custom:hui-horizontal-stack-card'
        - cards:
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/home-button.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_home
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/up-arrow.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_up
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/update-button.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_update
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/poweroff-button.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_power
              type: 'custom:button-card'
          type: 'custom:hui-horizontal-stack-card'
        - cards:
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/left-arrow.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_left
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/context-button.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_context
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/right-arrow.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_right
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/reboot-button.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_restart
              type: 'custom:button-card'
          type: 'custom:hui-horizontal-stack-card'
        - cards:
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/back-button.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_back
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/down-arrow.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_down
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/enter-button.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_enter
              type: 'custom:button-card'
            - color: transparent
              color_type: card
              entity: media_player.marvin
              entity_picture: /local/icons/animated/media-card/clean-button.png
              haptic: medium
              show_entity_picture: true
              show_name: false
              tap_action:
                action: call-service
                service: shell_command.marvin_clean
              type: 'custom:button-card'
          type: 'custom:hui-horizontal-stack-card'
      type: 'custom:hui-vertical-stack-card'
    filter:
      include:
        - entity_id: media_player.marvin
          state: idle
    show_empty: false
    type: 'custom:auto-entities'
  - cards:
      - cards:
          - color: transparent
            color_type: card
            entity: light.dita_2
            haptic: medium
            icon: 'fas:dog'
            name: Dita
            tap_action:
              action: call-service
              service: light.toggle
              service_data:
                entity_id: light.dita_2
            type: 'custom:button-card'
          - color: transparent
            color_type: card
            entity: light.marmaduke
            haptic: medium
            icon: 'fas:dog'
            name: Marmaduke
            tap_action:
              action: call-service
              service: light.toggle
              service_data:
                entity_id: light.marmaduke
            type: 'custom:button-card'
        type: 'custom:hui-horizontal-stack-card'
    type: 'custom:hui-vertical-stack-card'
  - entity: light.dita_2
    type: light
