icon: 'fas:users-cog'
title: Occupancy Settings
background: var(--background-image)
badges: []
cards:
  - entities:
      - entity: input_boolean.squiggley_home
      - entity: input_boolean.wee_bear_home
      - entity: input_boolean.dev_mode
    show_header_toggle: false
    title: Occupancy Dev
    type: entities
  - card:
      options:
        secondary_info: last-changed
      show_header_toggle: false
      title: Hoose Presence
      type: glance
    filter:
      include:
        - entity_id: sensor.house_occupancy_status
        - domain: person
          state: home
    show_empty: false
    type: 'custom:auto-entities'
  - entities:
      - entity: binary_sensor.front_doorbell_switch
        secondary_info: last-changed
      - entity: binary_sensor.home_off_switch
        secondary_info: last-changed
      - entity: binary_sensor.livingroom_on_off_switch
        secondary_info: last-changed
    title: Test Switches
    type: entities
  - cards:
      - entities:
          - input_select.home_users
          - input_text.send_message
        type: entities
      - color: green
        color_type: icon
        haptic: medium
        icon: 'fas:envelope'
        name: Send Message
        size: 20%
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.send_message_to_ui_selected_user
        type: 'custom:button-card'
    type: 'custom:hui-vertical-stack-card'
