icon: 'mdi:server'
title: Server Room
background: var(--background-image)
badges: []
cards:
  - cards:
      - action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.server_fan_relay
        color: auto
        color_type: icon
        entity: switch.server_fan_relay
        haptic: heavy
        icon: 'mdi:fan'
        name: Server Fan
        show_state: true
        state:
          - color: blue
            styles:
              icon:
                - animation: mysway 16s infinite
            value: 'on'
        style: |
          @keyframes mysway {
            0%, 100%{ transform: rotate(360deg);}
            0%{ transform: rotate(0deg); }
          }
        type: 'custom:button-card'
      - entity: sensor.server_room_temperature
        max: 100
        min: 0
        name: Server Room Temperature
        severity:
          green: 18
          red: 25
          yellow: 22
        theme: default
        type: gauge
      - entities:
          - entity: sensor.server_room_temperature
            name: Server Room
          - entity: sensor.dark_sky_temperature
            name: DarkSky Edinburgh
          - entity: switch.server_fan_relay
            name: Extractor Fan
        hours_to_show: 24
        refresh_interval: 0
        title: Server Room
        type: history-graph
      - entities:
          - input_number.server_fan_on_temperature
          - input_number.server_fan_off_temperature
        head:
          label: Server Fan Settings
          type: section
        type: 'custom:fold-entity-row'
    type: vertical-stack
  - cards:
      - entity: sensor.server_fan_voltage
        max: 100
        min: 0
        severity:
          green: 0
          red: 0
          yellow: 0
        theme: default
        type: gauge
      - entity: sensor.server_fan_current
        max: 100
        min: 0
        severity:
          green: 0
          red: 0
          yellow: 0
        theme: default
        type: gauge
      - entity: sensor.server_fan_power
        max: 100
        min: 0
        severity:
          green: 0
          red: 0
          yellow: 0
        theme: default
        type: gauge
    type: 'custom:hui-horizontal-stack-card'
  - entities:
      - entity: sensor.plex_total_bandwidth
      - entity: sensor.plex_lan_bandwidth
      - entity: sensor.plex_wan_bandwidth
    hours_to_show: 24
    type: 'custom:mini-graph-card'
    update_interval: 5
  - card:
      options:
        secondary_info: last-changed
      show_header_toggle: false
      title: Plex Stats
      type: entities
    filter:
      exclude:
        - entity_id: sensor.plex*_activity
          state: None
        - entity_id: sensor.plex*_stream_count
          state: ''
        - entity_id: sensor.plex*_stream_count_transcode
          state: ''
        - entity_id: sensor.plex*_direct_play
          state: ''
        - entity_id: sensor.plex*_direct_stream
          state: ''
        - entity_id: sensor.plex*_playing
          state: ''
        - entity_id: sensor.plex*_bandwidth
          state: unknown
        - entity_id: sensor.plex*_bandwidth
          state: '0.0'
        - entity_id: sensor.plex_stream_count*
          state: '0'
        - entity_id: sensor.plex*_bandwidth
          state: '0.0'
        - entity_id: sensor.plex_heart_of_gold
          state: '0'
      include:
        - entity_id: sensor.plex*
    show_empty: false
    type: 'custom:auto-entities'
