background: var(--background-image)
badges: []
cards:
  - entity: sensor.gateway_illumination_sensor
    max: 100
    min: 0
    severity:
      green: 0
      red: 0
      yellow: 0
    theme: default
    type: gauge
icon: 'mdi:stairs'
title: Hallway & Stairs
