icon: 'mdi:toilet'
path: toilet
title: Toilet
background: var(--background-image)
badges: []
cards:
  - cards:
      - entity: light.toilet_light_1
        name: Toilet One
        type: light
      - entity: light.toilet_light_2
        name: Toilet Two
        type: light
    type: horizontal-stack
