icon: 'fas:cloud-sun-rain'
path: weather
title: Weather
badges: []
cards:
  - entities:
      - entity: sensor.next_sunrise
        icon: 'mdi:weather-sunset-up'
        name: 'Next Sunrise:'
      - entity: sensor.next_sunset
        icon: 'mdi:weather-sunset-down'
        name: 'Next Sunset:'
      - entity: sensor.front_garden_temperature
      - entity: sensor.back_garden_temperature
    show_header_toggle: false
    title: Sunrise & Sunset
    type: entities
  - entity_current_conditions: sensor.dark_sky_icon
    entity_daily_summary: sensor.dark_sky_daily_summary
    entity_daytime_high: sensor.dark_sky_daytime_high_temperature_0d
    entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1d
    entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2d
    entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3d
    entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4d
    entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5d
    entity_forecast_icon_1: sensor.dark_sky_icon_1d
    entity_forecast_icon_2: sensor.dark_sky_icon_2d
    entity_forecast_icon_3: sensor.dark_sky_icon_3d
    entity_forecast_icon_4: sensor.dark_sky_icon_4d
    entity_forecast_icon_5: sensor.dark_sky_icon_5d
    entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_0d
    entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1d
    entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2d
    entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3d
    entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4d
    entity_humidity: sensor.dark_sky_humidity
    entity_pop: sensor.dark_sky_precip_probability
    entity_pop_1: sensor.dark_sky_precip_probability_1d
    entity_pop_2: sensor.dark_sky_precip_probability_2d
    entity_pop_3: sensor.dark_sky_precip_probability_3d
    entity_pop_4: sensor.dark_sky_precip_probability_4d
    entity_pop_5: sensor.dark_sky_precip_probability_5d
    entity_pop_intensity: sensor.dark_sky_precip_intensity
    entity_pressure: sensor.dark_sky_pressure
    entity_summary_1: sensor.dark_sky_summary_1d
    entity_summary_2: sensor.dark_sky_summary_2d
    entity_summary_3: sensor.dark_sky_summary_3d
    entity_summary_4: sensor.dark_sky_summary_4d
    entity_summary_5: sensor.dark_sky_summary_5d
    entity_sun: sun.sun
    entity_temperature: sensor.dark_sky_temperature
    entity_visibility: sensor.dark_sky_visibility
    entity_wind_bearing: sensor.dark_sky_wind_bearing
    entity_wind_speed: sensor.dark_sky_wind_speed
    large_icon_left_position: '-2em'
    locale: en
    old_daily_format: false
    show_beaufort: true
    time_format: 24
    tooltips: true
    type: 'custom:dark-sky-weather-card'
  - entities:
      - sensor.front_garden_temperature
      - sensor.back_garden_temperature
    hours_to_show: 168
    name: Outside Temperatures
    type: 'custom:mini-graph-card'
