heating_temperature:
  name: Temperature
  min: 5
  max: 25
  step: 1
  icon: mdi:thermometer
vestibule_temperature:
  name: Vestibule Temperature
  min: 7
  max: 25
  step: 1
  icon: mdi:home-thermometer
livingroom_temperature:
  name: Livingroom Temperature
  min: 7
  max: 25
  step: 1
  icon: mdi:home-thermometer
office_temperature:
  name: Office Temperature
  min: 7
  max: 25
  step: 1
  icon: mdi:home-thermometer
kitchen_temperature:
  name: Kitchen Temperature
  min: 7
  max: 25
  step: 1
  icon: mdi:home-thermometer
katrin_temperature:
  name: Katrin Temperature
  min: 7
  max: 25
  step: 1
  icon: mdi:home-thermometer
bedroom_temperature:
  name: Bedroom Temperature
  min: 7
  max: 25
  step: 1
  icon: mdi:home-thermometer
