normal_brightness:
  name: Normal Brightness
  min: 0
  max: 100
  step: 1
  icon: mdi:lightbulb-on
  
migraine_brightness:
  name: Migraine Brightness
  min: 0
  max: 100
  step: 1
  icon: mdi:lightbulb-on

night_light_brightness:
  name: Night Light Brightness
  min: 0
  max: 100
  step: 1
  icon: mdi:lightbulb-on