toilet_lights_timer:
  name: Toilet Lights Timer Duration
  icon: mdi:toilet
  min: 1
  max: 30
  step: 1

makeup_lights_duration:
  name: Makup Lights Duration
  min: 5
  max: 60
  step: 1
  icon: fas:paint-roller

night_light_duration:
  name: Night Light Duration
  min: 5
  max: 30
  step: 1
  icon: bha:led-strip