server_fan_on_temperature:
  name: Fan On
  initial: 26
  max: 35
  min: 15
  step: 0.5
  icon: mdi:thermometer

server_fan_off_temperature:
  name: Fan Off
  initial: 24
  max: 30
  min: 20
  step: 0.5
  icon: mdi:thermometer
