- platform: broadlink
  mac: 34:EA:34:58:A0:DF
  switches:
    - name: 'Kitchen Spiral Lights'
      command_on: 
        'JgBYAAABK5IVEBQSExITEhQRFBITEhMSFDYVNRQ1FDYVNRM2FDYVNRM3FTQWNBMSFBITEhMSExIUEhMSExIUNhM3EzYUNhM3EwAFIwABKUkTAAxdAAErSBUADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Brighter'
      command_on:
        'JgBYAAABKZUTEhIUEhMUERQSEhMUERQSEzYUNhE5FTQVNRE5ETgUNhQ2EhMSOBQRFBIRFBEUEhMVERE4EhQUNRI4EzcTNxE4EgAFJAABKUoRAAxeAAEpShUADQU= @'
    - name: 'Spiral Lights Sarker'
      command_on:
        'JgBYAAABKZUSExEUEhQRFBEUEhQRFBEUEjgTNxI3EzcTNxM3EjcTNxMSEhQROBMTERQRFBIUERQRORM3EhMRORQ1EzcTNxI3EwAFIgABK0kSAAxcAAErSBIADQU= @'
    - name: 'Spiral Lights Dark Red'
      command_on:
        'JgBgAAABK5MUERMTExITEhMTEhMTEhMSEzcTNxM3EjcTNxM3EjcTNxM3ERQUEhE4EhQRFBEUExMTEhM2EjgSFBE4EjgSOBE4EgAFIQABLUgUAAxbAAEqSRIADGAAASpIFAANBQAAAAAAAAAA @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Red'
      command_on:
        'JgBYAAABKpMTEhQRFBITEhQRFBEUEhMSFDYTNhQ2EzcTNhQ2EzcTNhQ2FBEUNhM3ExITEhQRFBITEhM2FBITEhQ2EzYUNhQ2EwAFIwABKkgVAAxcAAEpSRUADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Orange'
      command_on:
        'JgBYAAABK5MVEBMTEhMSExMTEhMSExIUEjcTNxI4EjcTNxQ2EjgUNRU1FBETNxITEzcVEBMTEhMSExE5FRASOBEUEjgVNRU0FgAFIQABKEsVAAxcAAEqSBQADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Light Orange'
      command_on:
        'JgBgAAABK5IVERITEhMSExMTEhMSExIUETgVNRQ2FTQVNRU1ETkVNBI4FRERFBE4FTUVEREUERQRFBE5FDYVEBEUETkVNRU0EgAFJQABK0cVAAxcAAEoSxEADGAAASpIFAANBQAAAAAAAAAA @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Yellow'
      command_on:
        'JgBYAAABKZUUERITEhQUERITFBIRFBITEjgSOBE4FDYUNhI4ETgSOBI4ERQUEhQRFDUSFBEUFBEVERQ1EjgSOBITEjgSOBE4EgAFJAABK0cTAAxeAAEsSBEADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Dark Green'
      command_on:
        'JgBYAAABK5ISFBEUFBEUEhQREhQTEhQREjgRORE4EjgUNhI4EjcUNhMTERQTEhM3ExITExMSExITNxM3EjcTExM2FDYUNhM3EwAFIwABKkkSAAxPAAErSBQADQU= @ '
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Green'
      command_on:
        'JgBYAAABKpMTEhMSFBEUEhMSExIUEhMSEzcTNhQ2EzcTNhQ2FDYTNhQSExITNxM2FBITEhMSFBEUNhQ2ExIUERQ2FDYUNRQ2FAAFIgABK0gUAAxdAAEqSBQADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Turquoise'
      command_on:
        'JgBYAAABKpMUERQSExIUERQSExITEhQRFDQWNhQ2EzYUNhQ2EzYUNhQRFBITNhQSEzYVERMSFBEUNhU1FRATNxUQFDYTNhU1FAAFIwABKUkTAAxfAAEqSBQADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Light Blue'
      command_on:
        'JgBYAAABKZUSFBEUERQRFREUERQRFREUETkVNBU1ETkVNRU0FTUVNRUQERQSFBE4FTUVEREUERQRORU1FTQVEREUETkUNRU1FQAFIgABKEsVAAxcAAEtRhIADQU= @ '
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Blue'
      command_on:
        'JgBgAAABLJEVEREUERQRFBIUERQRFBIUETgWNBE5ETkVNBU1ETkRORQRERQRFREUETkRFBEUERUROBU1FTUVNBYQEjcWNBQ2FAAFIwABLEcVAAxcAAEqSRQADFwAAStIFAANBQAAAAAAAAAA @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Dark Blue'
      command_on:
        'JgBYAAABLJISFBQRFBEUEhEUFBESFBEUEjgRORE4EjgSOBE5FDUSOBITEjgSExI4ExMUEREUEhQROBITFTUSFBQ1EjgSOBI4FAAFHAABLEgRAAxcAAEsSBIADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Dark Purple'
      command_on:
        'JgBYAAABKZQTEhMSFBITEhMSFBEVERQRFTUUNRU0FjUUNRU1FTUROREUEzcTNhQ2ExIUEhMSERQSOBMSFBITEhM2EjgTNxM3EwAFIwABKEoSAAxfAAErSBEADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Purple'
      command_on:
        'JgBYAAABKpMUEhQRFBESFBQREhMSFBEUETkUNRI4EjgUNRI4EjgSOBEUEjgROBIUFDUSFBEUEhMSOBQREhQROBIUETcWNRI4EgAFJQABK0gUAAxeAAEoShIADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Pink'
      command_on:
        'JgBgAAABK5MUERMTExITEhQQFRITEhMSFDYUNhQ2FDUUNhI4FDYUNRQSEzcTEhM3EzYUEhMSERUSNxMSEzcTExITEzYUNhQ2EwAFJAABKUkTAAxfAAEqSRQADF0AASxHFQANBQAAAAAAAAAA @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Light Pink'
      command_on:
        'JgBYAAABK5IUERURFBESExIUFBESExIUETgSOBI4FDYROBI4EjgSOBQRFDYRFBITEjgSFBEUFBESOBITEjgSOBEUFDYUNhE4FAAFIwABKkkUAAxeAAEnSxUADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights White'
      command_on:
        'JgBYAAABKJUSFBEUERQRFREUERQRFREUETkVNBU1FTUVNRE4EjgVNRU1FDUWEBI4FRARFBIUEhMSExEUEjgVERE4FTURORU1FQAFHgABLUcVAAxMAAEpSxUADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Flash'
      command_on:
        'JgBYAAABKJUVEREUERQSFBEUERURFBEUETkUNRI4FTUUNRU1FTURORU0FTUVNRU0FhARFBEUEhQRFBEUEhQRFBE5FTQVNRU1EQAFJQABLEYWAAxbAAEsRhMADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Strobe'
      command_on:
        'JgBYAAABKJUVEBEUEhQRFBEUEhQRFBEUETkVNRU0FTUVNRU0EjgVNRU1ETgVNRURETgVEREUERQRFBIUERQRORUQETkVNBY0FQAFIQABKUsVAAxaAAEoShYADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Fade'
      command_on:
        'JgBYAAABKZUUEREUExMRFBQPFhITEhQRFDYROBI4EzcTNxE4EzcTNxQ1EzcTEhQ2EzcTEhQRExMTEhQREzcTEhMTEzYUNhM3EgAFJAABLEcSAAxdAAErSBQADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    - name: 'Spiral Lights Smooth'
      command_on:
        'JgBYAAABKpMWEBMSExIUEhMSExITExMSEjgVNBU1FTUVNBM3FTUVNRU0FTUVEBMTEjcTExITEhMTExITEjgVNBUREjcVNRI4FQAFIQABKkkSAAxcAAEsSRMADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
        

