- platform: broadlink
  host: 192.168.13.80
  mac: 34:EA:34:58:A0:DF
  timeout: 15
  switches:
    spiral_lights:
      friendly_name: 'Kitchen Spiral Lights'
      command_on: 
        'JgBYAAABK5IVEBQSExITEhQRFBITEhMSFDYVNRQ1FDYVNRM2FDYVNRM3FTQWNBMSFBITEhMSExIUEhMSExIUNhM3EzYUNhM3EwAFIwABKUkTAAxdAAErSBUADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_brighter:
      command_on:
        'JgBYAAABKZUTEhIUEhMUERQSEhMUERQSEzYUNhE5FTQVNRE5ETgUNhQ2EhMSOBQRFBIRFBEUEhMVERE4EhQUNRI4EzcTNxE4EgAFJAABKUoRAAxeAAEpShUADQU= @'
    spiral_lights_darker:
      command_on:
        'JgBYAAABKZUSExEUEhQRFBEUEhQRFBEUEjgTNxI3EzcTNxM3EjcTNxMSEhQROBMTERQRFBIUERQRORM3EhMRORQ1EzcTNxI3EwAFIgABK0kSAAxcAAErSBIADQU= @'
    spiral_lights_darkred:
      command_on:
        'JgBgAAABK5MUERMTExITEhMTEhMTEhMSEzcTNxM3EjcTNxM3EjcTNxM3ERQUEhE4EhQRFBEUExMTEhM2EjgSFBE4EjgSOBE4EgAFIQABLUgUAAxbAAEqSRIADGAAASpIFAANBQAAAAAAAAAA @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_red:
      command_on:
        'JgBYAAABKpMTEhQRFBITEhQRFBEUEhMSFDYTNhQ2EzcTNhQ2EzcTNhQ2FBEUNhM3ExITEhQRFBITEhM2FBITEhQ2EzYUNhQ2EwAFIwABKkgVAAxcAAEpSRUADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_orange:
      command_on:
        'JgBYAAABK5MVEBMTEhMSExMTEhMSExIUEjcTNxI4EjcTNxQ2EjgUNRU1FBETNxITEzcVEBMTEhMSExE5FRASOBEUEjgVNRU0FgAFIQABKEsVAAxcAAEqSBQADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_lightorange:
      command_on:
        'JgBgAAABK5IVERITEhMSExMTEhMSExIUETgVNRQ2FTQVNRU1ETkVNBI4FRERFBE4FTUVEREUERQRFBE5FDYVEBEUETkVNRU0EgAFJQABK0cVAAxcAAEoSxEADGAAASpIFAANBQAAAAAAAAAA @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_yellow:
      command_on:
        'JgBYAAABKZUUERITEhQUERITFBIRFBITEjgSOBE4FDYUNhI4ETgSOBI4ERQUEhQRFDUSFBEUFBEVERQ1EjgSOBITEjgSOBE4EgAFJAABK0cTAAxeAAEsSBEADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_darkgreen:
      command_on:
        'JgBYAAABK5ISFBEUFBEUEhQREhQTEhQREjgRORE4EjgUNhI4EjcUNhMTERQTEhM3ExITExMSExITNxM3EjcTExM2FDYUNhM3EwAFIwABKkkSAAxPAAErSBQADQU= @ '
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_green:
      command_on:
        'JgBYAAABKpMTEhMSFBEUEhMSExIUEhMSEzcTNhQ2EzcTNhQ2FDYTNhQSExITNxM2FBITEhMSFBEUNhQ2ExIUERQ2FDYUNRQ2FAAFIgABK0gUAAxdAAEqSBQADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_turquoise:
      command_on:
        'JgBYAAABKpMUERQSExIUERQSExITEhQRFDQWNhQ2EzYUNhQ2EzYUNhQRFBITNhQSEzYVERMSFBEUNhU1FRATNxUQFDYTNhU1FAAFIwABKUkTAAxfAAEqSBQADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_lightblue:
      command_on:
        'JgBYAAABKZUSFBEUERQRFREUERQRFREUETkVNBU1ETkVNRU0FTUVNRUQERQSFBE4FTUVEREUERQRORU1FTQVEREUETkUNRU1FQAFIgABKEsVAAxcAAEtRhIADQU= @ '
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_blue:
      command_on:
        'JgBgAAABLJEVEREUERQRFBIUERQRFBIUETgWNBE5ETkVNBU1ETkRORQRERQRFREUETkRFBEUERUROBU1FTUVNBYQEjcWNBQ2FAAFIwABLEcVAAxcAAEqSRQADFwAAStIFAANBQAAAAAAAAAA @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_darkblue:
      command_on:
        'JgBYAAABLJISFBQRFBEUEhEUFBESFBEUEjgRORE4EjgSOBE5FDUSOBITEjgSExI4ExMUEREUEhQROBITFTUSFBQ1EjgSOBI4FAAFHAABLEgRAAxcAAEsSBIADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_darkpurple:
      command_on:
        'JgBYAAABKZQTEhMSFBITEhMSFBEVERQRFTUUNRU0FjUUNRU1FTUROREUEzcTNhQ2ExIUEhMSERQSOBMSFBITEhM2EjgTNxM3EwAFIwABKEoSAAxfAAErSBEADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_purple:
      command_on:
        'JgBYAAABKpMUEhQRFBESFBQREhMSFBEUETkUNRI4EjgUNRI4EjgSOBEUEjgROBIUFDUSFBEUEhMSOBQREhQROBIUETcWNRI4EgAFJQABK0gUAAxeAAEoShIADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_pink:
      command_on:
        'JgBgAAABK5MUERMTExITEhQQFRITEhMSFDYUNhQ2FDUUNhI4FDYUNRQSEzcTEhM3EzYUEhMSERUSNxMSEzcTExITEzYUNhQ2EwAFJAABKUkTAAxfAAEqSRQADF0AASxHFQANBQAAAAAAAAAA @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_lightpink:
      command_on:
        'JgBYAAABK5IUERURFBESExIUFBESExIUETgSOBI4FDYROBI4EjgSOBQRFDYRFBITEjgSFBEUFBESOBITEjgSOBEUFDYUNhE4FAAFIwABKkkUAAxeAAEnSxUADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_white:
      command_on:
        'JgBYAAABKJUSFBEUERQRFREUERQRFREUETkVNBU1FTUVNRE4EjgVNRU1FDUWEBI4FRARFBIUEhMSExEUEjgVERE4FTURORU1FQAFHgABLUcVAAxMAAEpSxUADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_flash:
      command_on:
        'JgBYAAABKJUVEREUERQSFBEUERURFBEUETkUNRI4FTUUNRU1FTURORU0FTUVNRU0FhARFBEUEhQRFBEUEhQRFBE5FTQVNRU1EQAFJQABLEYWAAxbAAEsRhMADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_strobe:
      command_on:
        'JgBYAAABKJUVEBEUEhQRFBEUEhQRFBEUETkVNRU0FTUVNRU0EjgVNRU1ETgVNRURETgVEREUERQRFBIUERQRORUQETkVNBY0FQAFIQABKUsVAAxaAAEoShYADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_fade:
      command_on:
        'JgBYAAABKZUUEREUExMRFBQPFhITEhQRFDYROBI4EzcTNxE4EzcTNxQ1EzcTEhQ2EzcTEhQRExMTEhQREzcTEhMTEzYUNhM3EgAFJAABLEcSAAxdAAErSBQADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
    spiral_lights_smooth:
      command_on:
        'JgBYAAABKpMWEBMSExIUEhMSExITExMSEjgVNBU1FTUVNBM3FTUVNRU0FTUVEBMTEjcTExITEhMTExITEjgVNBUREjcVNRI4FQAFIQABKkkSAAxcAAEsSRMADQU= @'
      command_off: 
        'JgBYAAABKpMVEBQSExITEhQSExITEhQSEzYVNRM3EzYUNhQ2EzYVNRUQFDYVNRUQFBITEhMSExIUNhUQFBITNhU1EzcTNhQ2FQAFHAABK0gVAAxTAAEqSBUADQU= @'
        

