- platform: template
  sensors:
    weather_summary:
      value_template: '{{ states.weather.met_office_corstorphine.state }}'
      entity_picture_template: "{{ state_attr('sensor.corstorphine_weather','icon') }}"
- platform: template
  sensors:
    weather_temperature:
      value_template: "{{ states.weather.met_office_corstorphine.state }}"
