downstairs_lights:
  name: Downstairs Lights
  entities: 
    - light.toilet_ceiling
    - light.vestibule_ceiling_lights
    - light.livingroom_ceiling
    - light.livingroom_lamps
    - light.office_ceiling
    - switch.office_spotlight
    - light.kitchen_ceiling
    - light.kitchen_strippers
    - light.kitchen_tree
    - light.spiral_lights
    - light.hall_ceiling
    - group.common_lights
#    - switch.back_garden_lights
#    - light.back_garden_lights
#    - light.front_garden_light # once we have a router for the back this is no longer required and we can use light.back_garden