- platform: snmp
  name: 'USG WAN in'
  host: 192.168.13.254
  baseoid: 1.3.6.1.2.1.31.1.1.1.6.2
  community: 'public'
  version: '2c'
  scan_interval: 10
- platform: snmp
  name: 'USG WAN out'
  host: 192.168.13.254
  baseoid: 1.3.6.1.2.1.31.1.1.1.10.2
  community: 'public'
  version: '2c'
  scan_interval: 10
- platform: statistics
  name: 'USG WAN in Stats'
  entity_id: sensor.usg_wan_in
  sampling_size: 4
  max_age:
    hours: 24
- platform: statistics
  name: 'USG WAN out Stats'
  entity_id: sensor.usg_wan_out
  sampling_size: 4
  max_age:
    hours: 24
- platform: template
  sensors:
    internet_in_mbps:
      value_template: "{{ (state_attr('sensor.usg_wan_in_stats_mean','change_rate')|float*8*(state_attr('sensor.usg_wan_in_stats_mean', 'sampling_size')-1)/1000000)|round(2) }}"
      unit_of_measurement: 'MBps'
      entity_id: sensor.usg_wan_in_stats_mean
    internet_out_mbps:
      value_template: "{{ (state_attr('sensor.usg_wan_out_stats_mean','change_rate')|float*8*(state_attr('sensor.usg_wan_out_stats_mean', 'sampling_size')-1)/1000000)|round(2) }}"
      unit_of_measurement: 'MBps'
      entity_id: sensor.usg_wan_out_stats_mean

