- platform: template
  sensors:
    stupid_box_status:
      friendly_name: "Stupid Box Status"
      value_template: >
        {% if is_state('media_player.livingroom_tv', 'on') and not is_state('media_player.zaphod_2', 'off') and is_state('media_player.squiggley_amp', 'on') %}
          on
        {% else %}
          off
        {% endif %}
