lighting_timer:
  name: Lighting timer
  icon: mdi:toggle-switch

makeup_lights:
  name: Makeup Lights
  icon: fas:paint-roller

night_light_stripper:
  name: Night Light Stripper
  icon: bha:led-strip