- platform: template
  sensors:
    bedroom_current_temperature:
      friendly_name: "Current Temperature"
      unit_of_measurement: 'C'
      value_template: "{{ state_attr('climate.bedroom', 'current_temperature') }}"
    bedroom_target_temperature:
      friendly_name: "Target Temperature"
      unit_of_measurement: 'C'
      value_template: "{{ state_attr('climate.bedroom', 'temperature') }}"
 