- platform: template
  sensors:
    katrin_current_temperature:
      friendly_name: "Current Temperature"
      unit_of_measurement: 'C'
      value_template: "{{ state_attr('climate.katrin', 'current_temperature') }}"
    katrin_target_temperature:
      friendly_name: "Target Temperature"
      unit_of_measurement: 'C'
      value_template: "{{ state_attr('climate.katrin', 'temperature') }}"
