- platform: template
  sensors:
    livingroom_current_temperature:
      friendly_name: "Current Temperature"
      unit_of_measurement: 'C'
      value_template: "{{ state_attr('climate.livingroom', 'current_temperature') }}"
    livingroom_target_temperature:
      friendly_name: "Target Temperature"
      unit_of_measurement: 'C'
      value_template: "{{ state_attr('climate.livingroom', 'temperature') }}"