- platform: template
  sensors:
    office_current_temperature:
      friendly_name: "Current Temperature"
      unit_of_measurement: 'C'
      value_template: "{{ state_attr('climate.office', 'current_temperature') }}"
    office_target_temperature:
      friendly_name: "Target Temperature"
      unit_of_measurement: 'C'
      value_template: "{{ state_attr('climate.office', 'temperature') }}"
