- platform: template
  sensors:
    vestibule_current_temperature:
      friendly_name: "Current Temperature"
      unit_of_measurement: 'C'
      value_template: "{{ state_attr('climate.vestibule', 'current_temperature') }}"
    vestibule_target_temperature:
      friendly_name: "Target Temperature"
      unit_of_measurement: 'C'
      value_template: "{{ state_attr('climate.vestibule', 'temperature') }}"