house_speakers:
    name: House Speakers
    icon: mdi:music
    entities:
      - media_player.livingroom_speaker
      - media_player.kitchen_speaker
      - media_player.office_speaker
      - media_player.office_display
