- platform: kodi
  host: 192.168.13.20
  name: marvin
  #username: !secret marvin_kodi_username
  #password: !secret marvin_kodi_password
  port: 8080
  turn_on_action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: "02:00:00:25:0F:01"
        broadcast_address: 255.255.255.255 
  turn_off_action:
    - service: kodi.call_method
      data:
        entity_id: media_player.marvin
        method: System.Shutdown
  