- platform: kodi
  host: 192.168.13.22
  name: slartibartfarst
  turn_on_action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: "B8:27:EB:89:00:47"
        broadcast_address: 255.255.255.255 
  turn_off_action:
    - service: kodi.call_method
      data:
        entity_id: media_player.slartibartfarst
        method: System.Shutdown