- platform: kodi
  host: 192.168.13.23
  name: SquiggleyVision
  port: 8080
  turn_on_action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: "84:39:BF:1E:6F:42"
        broadcast_address: 255.255.255.255 
  turn_off_action:
    - service: kodi.call_method
      data:
        entity_id: media_player.SquiggleyVision
        method: System.Shutdown