- platform: places
  name: Wee Bear Location
  devicetracker_id: device_tracker.claires_iphone_2
  options: street, street_number, postal_code, city, country
  map_provider: google
  map_zoom: 19
  home_zone: zone.home
  api_key: !secret wee_bear_openstreetmap_api
