host: 192.168.13.2
username: !secret influx_username
password: !secret influx_password
port: 8086
database: home_assistant
max_retries: 3
# default_measurement: state
# component_config_glob:
#   sensor*temperature:
#     override_measurement: temperature

