- platform: group
  name: Livingroom Lamps
  entities: 
    - light.dita
    - light.marmaduke_lamp
    - light.couch_lamp_one_2
    - light.couch_lamp_two_2
    - light.tv_lamp
    - light.door_lamp
  
- platform: group
  name: Table Lamps
  entities:
    - light.livingroom_lamps 