zaphod_audio_analogue: >
  curl -v -H "Content-type: application/json" -X POST -d '{"jsonrpc":"2.0","method":"Settings.SetSettingValue", "params":{"setting":"audiooutput.audiodevice","value":"iec958:CARD=Device,DEV=0"},"id":1}' http://zaphod.yeradonkey.com:8080/jsonrpc -u kodi:cayuga21
