esphome:
  name: bear_stripper
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "No Internet Access"
  password: "MikIsADonkey"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
sensor:
  - platform: wifi_signal
    name: "Bear Stripper Wifi"
    update_interval: 60s
#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w
light:
  - platform: rgbw
    name: "Bear Stripper"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w