esphome:
  name: dita
  platform: ESP8266
# Remove this line below if you do not want the bulb to remember the last on/off color state
  esp8266_restore_from_flash: true
  board: esp01_1m
  includes:
    - copychan.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dita Fallback Hotspot"
    password: "ee6hvXooegjZ"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

my9231:
 data_pin: GPIO13  
 clock_pin: GPIO15  
 num_channels: 6
 num_chips: 2 
 
output:
  - platform: my9231
    id: output_blue
    channel: 3
  - platform: my9231
    id: output_red
    channel: 5
  - platform: my9231
    id: output_green
    channel: 4
  - platform: my9231
    id: output_cw1
    channel: 1
  - platform: my9231
    id: output_cw2
    channel: 2
  - platform: custom
    type: float
    lambda: |-
      auto *copy = new CopyOutput();
      copy->channel_a = id(output_cw1);
      copy->channel_b = id(output_cw2);
      return {copy}; 
    outputs:
    - id: cw

light:
  - platform: rgbw
    name: "Dita"
    default_transition_length: 0s
    red: output_red
    green: output_green
    blue: output_blue
    white: cw

