substitutions:
  devicename: floor_lamp

esphome:
  name: $devicename
  esp8266_restore_from_flash: true
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Floor Lamp Fallback Hotspot"
    password: "jNu49O9vnbVM"

# Enable logging to ESPHome
logger:
  # Disable logging to serial
  baud_rate: 0

# Enable Home Assistant API
api:

# Setup OTA password
ota:
  password: !secret ota_password

# Define output pins
output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO14

# Define a light entity
light:
  - platform: rgbww
    name: $devicename
    id: $devicename
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: output_warm_white
    cold_white: output_cold_white
    cold_white_color_temperature: 6200 K
    warm_white_color_temperature: 2800 K
    effects:
      - random:
      - strobe:
      - flicker:
      - strobe:
          name: Alarm strobe
          colors:
          - state: True
            white: 0%
            brightness: 100%
            red: 100%
            green: 0%
            blue: 0%
            duration: 50ms
          - state: True
            white: 0%
            brightness: 100%
            red: 0%
            green: 100%
            blue: 0%
            duration: 50ms
          - state: True
            white: 0%
            brightness: 100%
            red: 0%
            green: 0%
            blue: 100%
            duration: 50ms
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
          - state: True
            brightness: 100%
            red: 100%
            green: 90%
            blue: 0%
            duration: 500ms
          - state: False
            duration: 250ms
          - state: True
            brightness: 100%
            red: 0%
            green: 100%
            blue: 0%
            duration: 500ms
      - lambda:
          name: My Custom Effect
          update_interval: 1s
          lambda: |-
            static int state = 0;
            auto call = id($devicename).turn_on();
            // Transtion of 1000ms = 1s
            call.set_transition_length(1000);
            if (state == 0) {
              call.set_rgb(1.0, 1.0, 1.0);
            } else if (state == 1) {
              call.set_rgb(1.0, 0.0, 1.0);
            } else if (state == 2) {
              call.set_rgb(0.0, 0.0, 1.0);
            } else {
              call.set_rgb(1.0, 0.0, 0.0);
            }
            call.perform();
            state += 1;
            if (state == 4)
              state = 0;