esphome:
  name: kitchen_tree
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "No Internet Access"
  password: "MikIsADonkey"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Kitchen Tree Button"
    on_press:
      - switch.toggle: kitchen_tree_fakebutton

switch:
  - platform: template
    name: "Kitchen Tree Relay"
    optimistic: true
    id: kitchen_tree_fakebutton
    turn_on_action:
    - switch.turn_on: kitchen_tree_relay
#    - light.turn_on: kitchen_tree_led
    turn_off_action:
    - switch.turn_off: kitchen_tree_relay
#    - light.turn_off: kitchen_tree_led
  - platform: gpio
    id: kitchen_tree_relay
    pin: GPIO12

#output:
#  - platform: esp8266_pwm
#    id: basic_green_kitchen_tree_led
#    pin:
#      number: GPIO13
#      inverted: True

#light:
#  - platform: monochromatic
#    name: "Kitchen Tree Green Led"
#    output: basic_green_kitchen_tree_led
#    id: kitchen_tree_led