## LOHAS RGBW Smart Bulb with ESPHome

esphome:
  name: office_two
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

my9231:
 data_pin: GPIO13  
 clock_pin: GPIO15  
 num_channels: 6
 num_chips: 1
 
output:
  - platform: my9231
    id: output_white
    channel: 0
  - platform: my9231
    id: output_blue
    channel: 1
  - platform: my9231
    id: output_green
    channel: 2
  - platform: my9231
    id: output_red
    channel: 3
  - platform: my9231
    id: output_warm_white
    channel: 4
  - platform: my9231
    id: output_cold_white
    channel: 5

light:
  - platform: rgbww
    name: "Office Two"
    default_transition_length: 0s
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_warm_white
    warm_white: output_cold_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
    effects:
      - strobe:
          name: Cold Strobe Effect
          colors:
            - state: True
              brightness: 80%
              blue: 100%
              red: 0%
              green: 0%
              duration: 500ms
            - state: False
              duration: 250ms
