esphome:
  name: server_extractor_fan
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Disable logging over USB
logger:
#  baud_rate: 0

# Enable Home Assistant API
api:

ota:

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff POW Button"
    on_press:
      - switch.toggle: fakebutton
  - platform: template
    name: "Server Fan Running"
    filters:
      - delayed_off: 15s
    lambda: |-
      if (isnan(id(power).state)) {
        return {};
      } else if (id(power).state > 4) {
        // Running
        return true;
      } else {
        // Not running
        return false;
      }

switch:
  - platform: template
    name: "Server Fan Relay"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12
    
output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "Server Fan Blue LED"
    output: pow_blue_led
    id: led

sensor:
  - platform: wifi_signal
    name: "Server Fan WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Server Fan Uptime"
  - platform: cse7766
    update_interval: 2s
    current:
      name: "Server Fan Current"
    voltage:
      name: "Server Fan Voltage"
    power:
      name: "Server Fan Power"
      id: power
      on_value_range:
        - above: 4.0
          then:
            - light.turn_on: led
        - below: 3.0
          then:
            - light.turn_off: led

text_sensor:
  - platform: version
    name: "Server Fan ESPHome Version"
