esphome:
  name: toilet_one
  platform: ESP8266
# Remove this line below if you do not want the bulb to remember the last on/off color state
  esp8266_restore_from_flash: true
  board: esp01_1m
  includes:
    - copychan.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Toilet One Fallback Hotspot"
    password: "ee6hvXooegjZ"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sm2135:
  data_pin: GPIO12
  clock_pin: GPIO14

# Individual outputs
output:
  - platform: sm2135
    id: output_red
    channel: 0
  - platform: sm2135
    id: output_green
    channel: 1
  - platform: sm2135
    id: output_blue
    channel: 2
  - platform: sm2135
    id: output_white
    channel: 3
  - platform: sm2135
    id: output_warmwhite
    channel: 4

light:
  - platform: rgbww
    name: "Sample RGBWW light"
    red: output_red 
    green: output_green 
    blue: output_blue 
    default_transition_length: 1s
    cold_white: output_white 
    warm_white: output_warmwhite 
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

