## LOHAS RGBW Smart Bulb with ESPHome

esphome:
  name: toilet_one
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  
my9231:
 data_pin: GPIO13  
 clock_pin: GPIO15  
 num_channels: 6
 num_chips: 1
 
output:
  - platform: my9231
    id: output_white
    channel: 0
  - platform: my9231
    id: output_blue
    channel: 1
  - platform: my9231
    id: output_green
    channel: 2
  - platform: my9231
    id: output_red
    channel: 3

light:
  - platform: rgbw
    name: "Toilet One"
    default_transition_length: 0s
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
