esphome:
  name: wee_bear_bed
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "No Internet Access"
  password: "MikIsADonkey"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
sensor:
  - platform: adc
    pin: A0
    name: "Wee Bear Bed Sensor"
    update_interval: 5s
