- platform: mqtt
  state_topic: 'sensor/bed/left'
  name: 'bed_left_value'

- platform: template
  sensors:
    mattias_bed_sensor:
      value_template: "{% if states('sensor.bed_left_value')| float > 20 %}Upptagen{% else %}tom{% endif %}"
      icon_template: "{% if states('sensor.bed_left_value')| float > 20 %}mdi:hotel{% else %}mdi:bed-empty{% endif %}"
